stages:
  preprocess:
    cmd: python src/preprocess/user_input.py --config_path params.yaml
    deps:
      - src/preprocess/user_input.py
    params:
      - dataset
      - preprocess
    outs:
      - src/artifacts/X.pkl
      - src/artifacts/y.pkl

  train:
    cmd: python src/train/user_input.py --config_path params.yaml
    deps:
      - src/train/user_input.py
      - src/artifacts/X.pkl
      - src/artifacts/y.pkl
    params:
      - train
      - model
    outs:
      - src/artifacts/trained_model_weights.h5
      - src/artifacts/production_model.keras