stages:
  preprocess:
    cmd: python src/preprocess/user_input.py --config_path params.yaml
    deps:
      - src/preprocess/user_input.py
    params:
      - dataset
      - preprocess
    outs:
      - src/artifacts/data.h5
      - src/artifacts/tokenizer.json
  train:
    cmd: python src/train/user_input.py --config_path params.yaml
    deps:
      - src/train/user_input.py
      - src/artifacts/data.h5
      - src/artifacts/tokenizer.json
    params:
      - mlflow
      - train
      - model
    outs:
      # - src/artifacts/trained_model_weights.h5
      # - src/artifacts/production_model.keras
      - src/artifacts/production_model