stages:

  preprocess:
    cmd: python -m src.data.preprocess
    deps:
      - src/data/preprocess.py
      - src/artifacts/data/Twitter/raw/train.csv
      - src/data/slangs.txt
    params:
      - dataset
    outs:
      - src/artifacts/data/Twitter/preprocessed/train.csv

  featurize:
    cmd: python -m src.data.main
    deps:
    - src/data/main.py
    params:
    - dataset
    - featurize
    outs:
    - src/artifacts/data.h5
    - src/artifacts/tokenizer.json

  train:
    cmd: python -m src.train.main
    deps:
    - src/train/main.py
    - src/artifacts/data.h5
    - src/artifacts/tokenizer.json
    params:
    - mlflow
    - train
    - model
    outs:
    - src/artifacts/recent:
        persist: true

  stage:
    cmd: python -m src.registry.stage
    deps:
    - src/registry/stage.py
    params:
    - train
    - model

  promote:
    cmd: python -m src.registry.promote
    deps:
    - src/registry/promote.py
    params:
    - train
    - model

