stages:

  preprocess:
    cmd: python src/data/preprocess.py 
    deps:
      - src/data/preprocess.py
      - data/Twitter/raw/train.csv
      - src/data/slangs.txt
    params:
      - dataset
    outs:
      - src/artifacts/data/preprocessed/train.csv

  featurize:
    cmd: python src/data/user_input.py 
    deps:
      - src/data/user_input.py
    params:
      - dataset
      - featurize
    outs:
      - src/artifacts/data.h5
      - src/artifacts/tokenizer.json

  train:
    cmd: python src/train/user_input.py 
    deps:
      - src/train/user_input.py
      - src/artifacts/data.h5
      - src/artifacts/tokenizer.json
    params:
      - mlflow
      - train
      - model
    outs:
      - src/artifacts/recent_model/

  stage:
    cmd: python src/registry/stage.py 
    deps:
      - src/registry/stage.py
      - src/artifacts/recent_model/

    
  promote:
    cmd: python src/registry/promote.py 
    deps:
      - src/registry/stage.py
      - src/artifacts/recent_model/

    
