mlflow:
  perform: "false"
  experiment_name: "2-RNN"
  tracking_uri: "http://localhost:5000"
  
dataset:
  path : data/Twitter/preprocessed/train.csv
  name : Twitter
  nrows : 30000

preprocess:
  method: "bow"       
  padding:
    padding: "post"
    truncating: "post"
    maxlen: 75            # since average words is 75

train:
  perform: "true"
  epochs: 30
  batch_size: 128
  test_size: 0.2

model:
  architecture : "rnn"
  embedding_dimension : 20     
