dataset:
  raw_path: /home/srirama/sr_proj/EmotionAnalysis/src/artifacts/data/Twitter/raw/train.csv
  preprocessed_path: /home/srirama/sr_proj/EmotionAnalysis/src/artifacts/data/Twitter/preprocessed/train.csv
  name: Twitter
  nrows_preprocess: null   # int or null
  text_column_index: 3
  label_column_index: 2

featurize:
  method: padding
  padding:
    padding: post
    truncating: post
    maxlen: 75

mlflow:
  perform: true
  experiment_name: 1-LSTM
  tracking_uri: http://localhost:5000

train:
  perform: true
  nrows_train: null
  epochs: 5
  batch_size: 400
  test_size: 0.4

model:
  architecture: lstm
  embedding_dimension: 20

registry:
  debug: true
