dataset:
  raw_path : data/Twitter/raw/train.csv
  preprocessed_path : src/artifacts/data/preprocessed/train.csv
  name : Twitter
  nrows_preprocess : None  # None or int
  text_column_index : 3 # Index begins from 0
  label_column_index : 2

featurize:
  method: "padding"       
  padding:
    padding: "post"
    truncating: "post"
    maxlen: 75            # since average words is 75

mlflow:
  perform: "true"
  experiment_name: "1-REG"
  tracking_uri: "http://localhost:5000" # Both are waste
  # tracking_uri: "sqlite:///mlflow.db" # 

train:
  perform: "true"
  nrows_train : None  # None or int
  epochs: 1
  batch_size: 400
  test_size: 0.4

model:
  architecture : "rnn"
  embedding_dimension : 40
